### ISSUE TITLE
(NeoForge 1.20.4) Mod asks for Forge despite saying NeoForge is supported

### ISSUE THREAD

**Issue by ChiesyCake** [vgskye/e4mc-minecraft-architectury#1]
Hi, I'm not sure if this is where I am meant to submit issues or if this place is maintained, but I figure it's worth a shot to submit this issue in hopes of it being fixed.
- - -
**Mod Version**: [1.18-] [Forge] 5.0.0 ([Modrinth](https://modrinth.com/mod/e4mc/version/5.0.0))
**Game Version**: 1.20.4
**NeoForge Version**: 20.4.235
- - -
Steps to Reproduce:
1. Add mod to 1.20.4 NeoForge pack
2. Attempt to boot game
3. Be met with error asking for Forge to be installed
- - -
![image](https://github.com/vgskye/e4mc-minecraft-architectury/assets/158130325/18a16432-d71f-4578-9eee-be7c17546283)

**Comment by vgskye** [comment]
the incorrect marking has been resolved, an actual NF port is currently not planned
