### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by RoonMoonlight** [vgskye/e4mc-minecraft-architectury#10]
Same as title, would be grateful if you are able to update this mod to 1.21 Update.

**Comment by Jash121212** [comment]
the current build works in 1.21

**Comment by RoonMoonlight** [comment]
> the current build works in 1.21

Will it be safe to use that mod for 1.21 release? Won't it cause some issues?

**Comment by vgskye** [comment]
I don't know, try and find out

**Comment by vgskye** [comment]
1.21... seems to work
