### ISSUE TITLE
"An Error Occurred In E4mC" Issue

### ISSUE THREAD

**Issue by TheGamingMarioD** [vgskye/e4mc-minecraft-architectury#11]
I'm trying to play with my brother using e4mc but when he uses the link it immediately tells him that the server cannot be found, and puts a message in my game saying "An Error Occurred In E4mC".

**Comment by abdogm** [comment]
Im having the same problem today 
few days ago it was working fine

**Comment by vgskye** [comment]
logs, please, I'm not clairvoyant
