### ISSUE TITLE
Version 3.2.0: An error occurred in e4mc. 

### ISSUE THREAD

**Issue by WildTiger404** [vgskye/e4mc-minecraft-architectury#12]
When I try to use e4mc 3.2.0 with minecraft 1.17.1 I've got the exception
javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

Could you update SSL certificate or give the instruction of how to do it by myself?

**Comment by vgskye** [comment]
please stop using v3
