### ISSUE TITLE
Support 1.7.10 and 1.12.2.

### ISSUE THREAD

**Issue by MagmaSlime123** [vgskye/e4mc-minecraft-architectury#13]
Title.

While Essential exists on 1.12.2, this mod isn't adding all the cosmetics/chat functionality and such that they do, so porting shouldn't be that hard. I hope.

**Comment by vgskye** [comment]
due to... internal issues, backports aren't planned.

**Comment by p1x3l101-10** [comment]
Not going to reopen this, but is the API stable? If I were to start a downstream fork, would the actual infrastructure be stable enough to assume it would be stable?

**Comment by MagmaSlime123** [comment]
> Not going to reopen this, but is the API stable? If I were to start a downstream fork, would the actual infrastructure be stable enough to assume it would be stable?

Would be nice if so.

**Comment by xhyrom** [comment]
I've managed to do it on 1.12.2 - https://github.com/xhyrom/e4mc-retro. Currently waiting for approval on [Modrinth](https://modrinth.com/mod/e4mc-retro).

Will work on 1.7.10 and other versions soon :)

**Comment by MagmaSlime123** [comment]
> I've managed to do it on 1.12.2 - https://github.com/xhyrom/e4mc-retro. Currently waiting for approval on [Modrinth](https://modrinth.com/mod/e4mc-retro).
> 
> Will work on 1.7.10 and other versions soon :)

Why use Legacy Fabric? Almost no one uses that, and 1.12/1.7.10's only real use is for Forge mods that never updated.

**Comment by xhyrom** [comment]
> > I've managed to do it on 1.12.2 - https://github.com/xhyrom/e4mc-retro. Currently waiting for approval on [Modrinth](https://modrinth.com/mod/e4mc-retro).
> > Will work on 1.7.10 and other versions soon :)
> 
> Why use Legacy Fabric? Almost no one uses that, and 1.12/1.7.10's only real use is for Forge mods that never updated.

Because it's not that big deal to also support other mod loaders 🤷. Maybe someone will find it useful :D
