### ISSUE TITLE
c4mc dosnt work

### ISSUE THREAD

**Issue by savvacorgi** [vgskye/e4mc-minecraft-architectury#14]
screnshot
![2024-06-28_15 40 28](https://github.com/vgskye/e4mc-minecraft-architectury/assets/143608608/070ad79c-6552-4b0d-98e5-24da8c3e7a2d)
logs
[latestlog.txt](https://github.com/user-attachments/files/16029758/latestlog.txt)

**Comment by vgskye** [comment]
...how did yo... oh, pojav, yeah no I'm not dealing with that
