### ISSUE TITLE
Client-Side Mods Avoiding Other People To Join

### ISSUE THREAD

**Issue by Fyoncle** [vgskye/e4mc-minecraft-architectury#15]
If you don't have the EXACT mods with the person trying to join, even tho you have a client-side mod, they cannot join, any fix for this?

**Comment by vgskye** [comment]
take it up to forge(I assume it's forge since iirc they're the only one to check), out of scope here

**Comment by Fyoncle** [comment]
> take it up to forge(I assume it's forge since iirc they're the only one to check), out of scope here

BRO IM USING FABRIC-

**Comment by vgskye** [comment]
point still stands, e4mc doesn't do anything related to this

**Comment by Fyoncle** [comment]
> point still stands, e4mc doesn't do anything related to this

But it blocks people from joining unless they have the client-side mods you do too

**Comment by vgskye** [comment]
e4mc doesn't, it's whatever other mods you're using

**Comment by Fyoncle** [comment]
> e4mc doesn't, it's whatever other mods you're using

No its literally e4mc :(

**Comment by vgskye** [comment]
...you're arguing against the person who wrote the entire mod about what the mod does?

**Comment by Fyoncle** [comment]
> ...you're arguing against the person who wrote the entire mod about what the mod does?

but its just... whatever i think ill try it once again with only e4mc installed then spawn here again
