### ISSUE TITLE
Self Host

### ISSUE THREAD

**Issue by watermelon0guy** [vgskye/e4mc-minecraft-architectury#2]
I'm sorry if I didn't see a link somewhere, but I was trying to find the source code of the server. Is there a possibility of an self-host?

**Comment by vgskye** [comment]
the server source is published at http://git.skye.vg/me/quiclime, but deployment is... nontrivial and there's no machinery inside the mod to change the servers other than recompilation iirc

**Comment by vgskye** [comment]
documentation around the internals is unfortunately sparse rn; I am terrible at documenting my work

**Comment by watermelon0guy** [comment]
Thx, maybe i'll try :D
Anyway thx for cool mod (and my hat off for the Rust server)
