### ISSUE TITLE
Lying about License

### ISSUE THREAD

**Issue by sylv256** [vgskye/e4mc-minecraft-architectury#20]
This mod's Modrinth page claims it is MIT. However, the mod in question has no `LICENSE` file in the root directory.

This effectively means two things:
1. The mod is actually All Rights Reserved
2. You are lying about the mod's license.

I'm not saying you should make this one license or the other, I'm just saying that it's inconsistent.

**Comment by sylv256** [comment]
I've been informed that a potential interpretation of this is that the mod binary is redistributable but the source code is not. If that's what you intended, it would be wise to specify that in the `README.md`.

**Comment by vgskye** [comment]
oh, whoops, the pre-rewrite version had the correct license files, seems like I forgot to add them in this repo. the code can also be considered MIT; I'll add the LICENSE file soon

**Comment by vgskye** [comment]
fixed in 84cb784
