### ISSUE TITLE
[Feature Request]: Ability to generate proxy link when using mod serverside hosting a server

### ISSUE THREAD

**Issue by NinDevs** [vgskye/e4mc-minecraft-architectury#25]
It would be lovely to be able to host a server without having to have the game open, and use the mods functions to generate a shareable ip for friends to connect to server w/o port-forwarding. This gives the freedom of managing the server separately while still benefitting from e4mc.

Or, perhaps this is possible and I am not aware of how to do this? If this does work, can a command be added like '/e4mc link' or '/e4mc ip' to get the address? Better yet, upon joining the server, the first message in chat history should be the server-link. If that's too revealing, that chat message could be limited to OPs upon joining.

**Comment by vgskye** [comment]
not planned
