### ISSUE TITLE
my friends from Russia can't host the server

### ISSUE THREAD

**Issue by PaleFish** [vgskye/e4mc-minecraft-architectury#28]
I have 2 friends who tried to create a server via e4ms but they got this error. I live in Ukraine and have never had such problems. We have the same mod pack, so I won’t say that it’s a matter of extraneous mods. Tell me, maybe the problem is that they live in Russia 
![Screenshot_201](https://github.com/user-attachments/assets/ace98a49-57e9-4040-9238-7703307ba1eb)

**Comment by vgskye** [comment]
please send actual logs

**Comment by PaleFish** [comment]
[latest.log](https://github.com/user-attachments/files/16361899/latest.log)

there

**Comment by vgskye** [comment]
Please confirm that https://broker.e4mc.link/getBestRelay is reachable by browser

**Comment by PaleFish** [comment]
My friend reported that the address is available in the browser. Or maybe I misunderstood your words

**Comment by PaleFish** [comment]
My friend said that e4mc addresses are available in the browser. Maybe I misunderstood your words

**Comment by Sw1tl3** [comment]
используй впн, видимо айпи из России не проходит

**Comment by NightWolfXCore** [comment]
> My friend reported that the address is available in the browser. Or maybe I misunderstood your words

Также испытал проблему с использованием мода. Когда разработчик поделился ссылкой, то вылезала ошибка "dns_probe_finished_nxdomain". Её нужно исправить. Как я делал? Нашёл гайд в гугле насчёт сброса ДНС и очистки айпи (касаемо ДНС надо смотреть, так как остальное полная фигня) - [Клик](https://remontka.pro/dns-probe-finished-nxdomain/)

Именно на смене параметров DNS у меня всё решилось. Выставил вручную эти сервера - 1) для IPv4 - 77.88.8.8 и 77.88.8.1
2) для IPv6 - 2a02:6b8::feed:0ff и 2a02:6b8:0:1::feed:0ff

Только после этого сайт и, соответственно, мод заработали на ура. Попробуйте так решить.

**Comment by Duck4Mann** [comment]
Случайно решил эту проблему используя GoodbyeDPI через russia_blacklist. Так как проверял с одного компьютера, то не уверен в том кому нужно играть с запущенным GDPI, хосту или гостям.

**Comment by Nextun3** [comment]
gust download zapret-discord-youtube, open list-general.txt, tipe e4mc.link, eu.e4mc.link and us.e4mc.link, save, open general (ALT) and it works

**Comment by vgskye** [comment]
seems like this is an issue on russia's end, closing

**Comment by timishavet** [comment]
> gust download zapret-discord-youtube, open list-general.txt, tipe e4mc.link, eu.e4mc.link and us.e4mc.link, save, open general (ALT) and it works

That didn't work out for me... Works with VPN though, but I don't want play through VPN

**Comment by Artem19846578** [comment]
English: Change Forge in Minecraft to Fabric. Or download sinytra connector, and change e4mc version to 5.2.1.
Russian: Попробуй изменить Forge на Fabric в Майнкрафт. Или установи sinytra connector, и измени версию e4mc на 5.2.1
