### ISSUE TITLE
Usage with simple voicechat

### ISSUE THREAD

**Issue by xana43** [vgskye/e4mc-minecraft-architectury#3]
So, I've recently been tasked with creating a modpack for some friends and I to play on. one of the things that's a mainstay is the mod Simple voice chat, and while I do have another server PC that is going to be repurposed very soon, I found this mod and it seems to be good for multiple things, 1. it's good at guaging how full the modpack is so we know what area we need to improve on 2. it makes making servers easier. However the issue I've been having is that when any of my friends join they are unable to connect to the VC at least with what i've tried thus far. According to the logs the voice chat is forced to run under the same port as the LAN server itself, which is not good, because even on the modpage is says "it's not recommended for the voice chat server port to be same as the actual server port". I've tried setting ports everywhere in all the available configs, and there isn't even any configs for this mod at all. Other than that this mod is fantastic, is there any way to solve this? a work around for some kind of fix?

**Comment by vgskye** [comment]
e4mc cannot and will never support mods that require a sideband connection such as Simple Voice Chat.
