### ISSUE TITLE
e4mc failed to load on 1.21

### ISSUE THREAD

**Issue by execOQ** [vgskye/e4mc-minecraft-architectury#33]
Tried to use the mod on 1.21 forge, but with installed e4mc got the error connected with mixins. 

logs: https://pastebin.com/0mUefsvv

error:
![image](https://github.com/user-attachments/assets/a9c2822b-41ff-4995-8869-6748dd153fa5)

**Comment by bubzilla** [comment]
skill issue

**Comment by vgskye** [comment]
use neo. forge 1.21 is not supported.

**Comment by bubzilla** [comment]
why did my comment get put marked as off-topic? he really JUST has a skill issue
