### ISSUE TITLE
exception on boot, probably too many mods 

### ISSUE THREAD

**Issue by AqlCaraMsm** [vgskye/e4mc-minecraft-architectury#37]
hewo
logs: https://mclo.gs/jpqWm0F

just tried adding it on Better Minecraft (Forge), doesn't boot. every time i run it the end of the following line shows a different mod, so it could an incompatibility/mistake on my part relating to multiple mods
&emsp;Caused by: java.lang.module.ResolutionException: Modules e4mc_minecraft and luna export package io.netty.incubator.codec.quic to module openpartiesandclaims

tyyy :3

**Comment by vgskye** [comment]
I've worked with Luna Pixel Studios so e4mc is included in Luna, so it's conflicting with... basically itself
