### ISSUE TITLE
e4mc not giving ip after opening server

### ISSUE THREAD

**Issue by teh-ches-noddle** [vgskye/e4mc-minecraft-architectury#44]
I am trying to play with a friend and the mod worked fine two days ago.  Nothing's changed to my knowledge but when I open the server all I get is the port number and below it the message "text.e4mc_minecraft.domainAssignedtext.e4mc_minecraft.clickToStop".
I tried downgrading the mod to see if that was the issue but that didn't do anything.  Are the servers just unavailable right now?

Edit: Nevermind it wasn't an issue with e4mc

**Comment by alsowski** [comment]
Hello bro, that happens to me, how did you solve it?
