### ISSUE TITLE
Host Cannot Have Client-Side Mods

### ISSUE THREAD

**Issue by Fyoncle** [vgskye/e4mc-minecraft-architectury#48]
When host haves a client-side mod, my friend get this error;
![image](https://github.com/user-attachments/assets/870f4b43-afa7-4fad-ab20-90faba88558f)

But when i join him while having a client-side mod but he doesn't, i can join.

**This tested in a minimal instance, there was no other mods added except Fabric API.**

**Comment by pintux98** [comment]
Hi, I just had the same issue... can it be this maybe? 

I was trying to show a mod to a friend and I had 3D skin layers mod. For some reason he was not able to join mine, but I was able to join his world . 

Later I found that removing my CLIENT side mod, fixed the issue.. why is e4mc like trying to send packets related to something only client side?

**Comment by bradcarnage** [comment]
this is due to bad implementation of your client-side mod. not this mod's problem.

**Comment by Fyoncle** [comment]
> this is due to bad implementation of your client-side mod. not this mod's problem.

What proves this?

**Comment by vgskye** [comment]
e4mc uses the exact same code path as vanilla LAN servers. it does not and will never touch vanilla packet handling/sending pipeline and any issue is due to the other mod's side.
