### ISSUE TITLE
e4mc us

### ISSUE THREAD

**Issue by yeeterlol** [vgskye/e4mc-minecraft-architectury#5]
tried to connect via e4mc on us so my wife can play with me ^_^
doesn't seem to work, even tried on another account :(

**Comment by grinreo** [comment]
@yeeterlol what is the error?

**Comment by jucaTHOR** [comment]
It is now being worked on

**Comment by jucaTHOR** [comment]
skyevg — Today at 3:08 PM
hopefully it's fixed, I'm currently too tired to test
jucaTHOR — Today at 3:08 PM
ill test it
it works

**Comment by yeeterlol** [comment]
fixed
