### ISSUE TITLE
my friends e4mc server that we made for the friend group suddenly stopped letting us connect to eachother's worlds after updating every mod in the modpack we made with curseforge client

### ISSUE THREAD

**Issue by TheGameSquad22** [vgskye/e4mc-minecraft-architectury#51]

**Comment by vgskye** [comment]
logs

**Comment by TheGameSquad22** [comment]
i pressed enter on accident after the title since im not used to github so lemme write this

**Comment by TheGameSquad22** [comment]
the logs and modlist are right here in this reddit post i made yesterday 

https://www.reddit.com/r/feedthebeast/comments/1fzcfea/friend_group_kitchen_sink_modpack_suddenly/

a little lazy to copy and paste the logs and modlist since they're so aggreviously long

**Comment by vgskye** [comment]
please upload logs to https://mclo.gs

**Comment by vgskye** [comment]
also, doesn't seem to be an e4mc issue

**Comment by TheGameSquad22** [comment]
oh alr then sorry to bother, just had nowhere else to turn

**Comment by TheGameSquad22** [comment]
logs exceed the maximum characters, putting the paste into a text file instead ig in case you still want to check it out

[New Text Document.txt](https://github.com/user-attachments/files/17321486/New.Text.Document.txt)
