### ISSUE TITLE
Friend can't connect

### ISSUE THREAD

**Issue by Yato437** [vgskye/e4mc-minecraft-architectury#52]
[latest.log](https://github.com/user-attachments/files/17349437/latest.log)

Friend can't connect to me for some reason despite others being able to.

He keeps getting this error on his side:
![thing](https://github.com/user-attachments/assets/3437073e-a849-45f0-bc38-e3e8f75b7384)

**Comment by Yato437** [comment]
I should add that I also can't join him when he hosts his own lan world

**Comment by vgskye** [comment]
ah, pirated, not supported.
