### ISSUE TITLE
Doesn't connect.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [vgskye/e4mc-minecraft-architectury#53]
Although https://github.com/vgskye/e4mc-minecraft-architectury/blob/b23c28b243bd094dbd7e253d4fb12a4d61590181/README.md#usage states:

> Open to LAN as normal.

...this doesn't function for @JaredRichardWilliam and I:

1. > ![image](https://github.com/user-attachments/assets/eddbbc18-aefb-4aab-b8ee-461bf730b779)
1. > ![image](https://github.com/user-attachments/assets/52f3e497-1d82-41e0-96aa-04c15d236922)

However, we're able to connect via LAN IP addresses.

**Comment by vgskye** [comment]
omit the port.

**Comment by RokeJulianLockhart** [comment]
@vgskye, thanks. That remediates this problem. However, it still doesn't function - I'll file a separate report.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/vgskye/e4mc-minecraft-architectury/issues/53#issuecomment-2423483219

@vgskye, thanks. That at least allows me to connect. However, it still doesn't function - I've filed https://github.com/vgskye/e4mc-minecraft-architectury/issues/54#issue-2599634222.
