### ISSUE TITLE
Its not showing any IP

### ISSUE THREAD

**Issue by mateoangel99** [vgskye/e4mc-minecraft-architectury#55]
I started the new world, and do all the stuff, but the mod is no generating any IP on the chat.

**Comment by vgskye** [comment]
logs, screenshots, anything?

**Comment by mateoangel99** [comment]
[2024-10-22-7.log.gz](https://github.com/user-attachments/files/17483802/2024-10-22-7.log.gz)
![2024-10-22_20 07 25](https://github.com/user-attachments/assets/ab1f484b-3ec5-434b-8200-2d0c9500c048)

it just doesnt do anything

**Comment by vgskye** [comment]
log says you don't have e4mc installed?

**Comment by mateoangel99** [comment]
nop, it must be installed, because it gives me the option to open the LAN. It just doesnt generate the IP

**Comment by vgskye** [comment]
...open to lan is vanilla?

**Comment by mateoangel99** [comment]
If u mean the vanilla menu, then yes

**Comment by vgskye** [comment]
why are you claiming that a vanilla button proves that you have e4mc installed. you do not have e4mc installed in the provided log.

**Comment by mateoangel99** [comment]
sorry, didnt mean to bother. I also followed the steps to see how to install it, but it still not giving me the IP

It could be the zone where im located?
