### ISSUE TITLE
Work with cracked clients?

### ISSUE THREAD

**Issue by zjavierf** [vgskye/e4mc-minecraft-architectury#56]
My friend uses cracked minecraft and im not sure if thats whats causing the issue with him joining

**Comment by Fyoncle** [comment]
E4MC does not support cracked clients and will never support it.

**Comment by PrasadHendry** [comment]
> My friend uses cracked minecraft and im not sure if thats whats causing the issue with him joining

use lanpropertites mod and have it on offline + uuid fix

**Comment by PrasadHendry** [comment]
Is there a way to preserve the server or game file properties for continuing individual play after a session.

Like sharing saves / world files?

**Comment by The4codeblocks** [comment]
> use lanpropertites mod and have it on offline + uuid fix

well, thanks?

**Comment by Fyoncle** [comment]
> > use lanpropertites mod and have it on offline + uuid fix
> 
> well, thanks?

Tried, it works perfectly fine.

**Comment by electikos** [comment]
it doesn't work, on not local network
