### ISSUE TITLE
My friends can't join

### ISSUE THREAD

**Issue by grinreo** [vgskye/e4mc-minecraft-architectury#6]
When I create a LAN port, I get the link and send it to my friends. However, when they try to join, they can't because Minecraft says "connection lost." I don't know what to do. Can someone help me?

**Comment by acewins727** [comment]
I think the thing is broken, we'll have to wait for it to be fixed ig

**Comment by acewins727** [comment]
what servers are you on ?

**Comment by grinreo** [comment]
@acewins727 i play on my survival world, if you mean that

**Comment by grinreo** [comment]
@acewins727 
Does the mod work for you?

**Comment by acewins727** [comment]
it doesn't since yesterday

**Comment by acewins727** [comment]
and I meant what e4mc servers, like EU, US, OC and JP

**Comment by grinreo** [comment]
@acewins727 same, doesn't work since yesterday and i use EU servers

**Comment by acewins727** [comment]
I'm trying to know if it's a EU problem or a e4mc problem

**Comment by acewins727** [comment]
the server status page says it's working well so the servers are working

**Comment by acewins727** [comment]
https://status.e4mc.link/

**Comment by acewins727** [comment]
but just now there have been a few orange dots which would normally mean people have been connecting

**Comment by acewins727** [comment]
the japanese one just had a red dot show up so probably this one is working

**Comment by acewins727** [comment]
it looks like people are using it rn but it still doesn't work for me  
what country do you live in ?

**Comment by acewins727** [comment]
maybe doing /e4mc restart over and over and trying to get a working one could work...??

**Comment by grinreo** [comment]
I live in germany, and you?

**Comment by acewins727** [comment]
france, so it's not a country thing either

**Comment by acewins727** [comment]
I really think we have to wait until it works again, I've tried it with only e4mc and it doesn't work

**Comment by grinreo** [comment]
yea, i hope it will fixed

**Comment by acewins727** [comment]
maybe tomorrow ? I hope

**Comment by jucaTHOR** [comment]
I messaged the dev, a few hours ago.
It is now being worked on.

**Comment by acewins727** [comment]
damn, I didn't find where to message her directly

**Comment by jucaTHOR** [comment]
skyevg — Today at 3:08 PM
hopefully it's fixed, I'm currently too tired to test
jucaTHOR — Today at 3:08 PM
ill test it
it works

**Comment by acewins727** [comment]
ok nice

**Comment by grinreo** [comment]
i'll test if it works
