### ISSUE TITLE
Failed to download native library

### ISSUE THREAD

**Issue by lorgll** [vgskye/e4mc-minecraft-architectury#60]
When I try to open a server (or use the restart command) I get this log feedback https://pastebin.com/W0vWEzdU

**Comment by vgskye** [comment]
please confirm that https://natives.e4mc.link/ is reachable by browser, if it's unreachable, this is your internet's issue and I cannot assist.

**Comment by lorgll** [comment]
Oh I tried to connect to it by my browser many times and it didn't work. But I was able to reach the broker link. So I assumed that the natives one was not meant to be reachable. I'll try to speak to my provider then
