### ISSUE TITLE
random issue i found when i was trying to join my brother who was on 1.20.1 and i was on 1.21.1 (btw it was a e4mc server) when i tried joining it had this error message

### ISSUE THREAD

**Issue by padnar** [vgskye/e4mc-minecraft-architectury#61]
<img width="1383" alt="Screenshot 2024-11-04 at 2 08 40 PM" src="https://github.com/user-attachments/assets/cd617440-1c65-45de-b5ad-a960d20d89e7">

**Comment by vgskye** [comment]
not on e4mc's side
