### ISSUE TITLE
On the latest update of all the mods ten, it is impossible to joinwwith e4mc 

### ISSUE THREAD

**Issue by lolLegend54** [vgskye/e4mc-minecraft-architectury#64]
the 2 errors I managed to catch.:
java.net.SocketException: Connection reset
---- Minecraft Network Protocol Error Report ----
// Too many suspicious packets

Time: 2024-11-22 12:34:38
Description: Packet handling error

java.net.SocketException: Connection reset

**Comment by vgskye** [comment]
full logs please
