### ISSUE TITLE
Custom domain.

### ISSUE THREAD

**Issue by F-alling** [vgskye/e4mc-minecraft-architectury#8]
Can I use a custom domain instead of e4mc.us? I have control over my domain.

**Comment by vgskye** [comment]
not unless you self host a relay, in which case why not just put the server there

**Comment by famellad** [comment]
Without going into the philosophical question of why host a relay rather than a server, how would one do that? I can't find the relay component repo in your profile :(

**Comment by vgskye** [comment]
> Without going into the philosophical question of why host a relay rather than a server, how would one do that? I can't find the relay component repo in your profile :(

https://git.skye.vg/me/quiclime
